name: Ecomm- User-Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: rhel_arm

    steps:
      - name: Import secrets hashicorp 
        uses: hashicorp/vault-action@v2.4.0
        with: 
          url: ${{secrets.VAULT_SERVER}}
          token: ${{secrets.VAULT_TOKEN}}
          tlsSkipVerify: true  
          secrets: | 
            dockerhub/data/dockerhub username | DOCKER_USERNAME;   
            dockerhub/data/dockerhub token |DOCKER_TOKEN;
            
      - name: Check out  repo
        uses: actions/checkout@v4
        with:
          repository: manupanand-freelance-developer/ecomm-user
          ref: ${{github.ref}} #ref- branches
          


      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ env.DOCKER_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./idp-ui
      #     file: ./idp-ui/Dockerfile
      #     platforms: linux/amd64 # target image
      #     push: true
      #     tags: manupanand/test:latest
      - name: Login docker 
        run: |
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      
      - name: Build Docker image
        run: |
          
          rm -rf $HOME/dockerbuild.log
          touch $HOME/dockerbuild.log
          chmod 775 $HOME/dockerbuild.log
          docker buildx build --platform linux/arm64 -t manupanand/ecomm-user:latest --push . 2>&1| tee -a $HOME/dockerbuild.log
    